config/routes.rb
Newsample::Application.routes.draw do
  resources :users 
  resources :sessions, :only => [:new, :create, :destroy]
  resources :members
  resources :localevents
  resources :resources
  
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy' 

  match '/contact', :to => 'pages#about'
  
  match '/create_member', :to => 'members#new'
  match '/edit_member', :to => 'members#edit'
  match '/list_members', :to => 'members#index'
  match '/add_member', :to => 'members#new'
  
  match '/add_event', :to => 'localevents#new'
  match '/show_event', :to => 'localevents#show'
  match '/list_events', :to => 'localevents#index'
  match '/edit_event', :to => 'localevents#edit'

  match '/add_resource', :to => 'resources#new'
  match '/list_resources', :to => 'resources#index'
  match '/edit_resource', :to => 'resources#edit'
  
  match '/admin', :to => 'pages#admin'
  match '/construction', :to => "pages#construction"
  root :to => 'pages#home'
end

          

app/models/localevent.rb
# == Schema Information
#
# Table name: localevents
#
#  id          :integer         not null, primary key
#  when        :string(255)
#  time        :string(255)
#  location    :string(255)
#  contact     :string(255)
#  name        :string(255)
#  description :string(255)
#  website     :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#

class Localevent < ActiveRecord::Base
  attr_accessible :when, :location, :contact, :name, :description, :website
  
end

app/controllers/localevents_controller.rb
class LocaleventsController < ApplicationController
  before_filter :admin_user,  :only => [:new, :create, :destroy, :edit]

  def new
    @title = "Create New Event"
    @newevent = Localevent.new
  end
  
  def edit
    @title = "Edit Event"    
    @event = Localevent.find(params[:format])
  end

  def show
    @event = Localevent.find(params[:id])
    @title = "Show Event"
  end

  def index
    @title = "Drug Free Draper Events"
    @events = Localevent.all
  end

  def update
    @event = Localevent.find(params[:id])
    
    # update model entry with validation
    if @event.update_attributes(params[:localevent])
      flash[:success] = "Event updated."
      
      redirect_to @event 
    else
      flash[:failure] = "ERROR: Event NOT updated."
      @title = "Edit Event"
      render :action => "edit"
    end 
  end
  
  def create
    @newevent = Localevent.new(params[:localevent])
    
    if @newevent.save
      flash[:success] = "Event Saved!"
      redirect_to list_events_path 
    else
      flash[:failure] = "ERROR: Event NOT created."
      @title = "Create New Event"
      render 'new'
    end
  end
  
  def destroy
    Localevent.find(params[:id]).destroy
    flash[:success] = "This Event was destroyed."
    redirect_to list_events_path
  end

  private
  def admin_user
    redirect_to(root_path) if current_user.nil? || !current_user.admin?
  end

end

app/helpers/localevents_helper.rb
module LocaleventsHelper
end

app/views/localevents/_event_entry.erb
<tr>
	<td width="200px" class="eventcolumn">
	    <strong>Name: </strong><br />
		<%= object.name %><br /><br />
		<strong>Date/Time: </strong><%= object.when %><br />
		<strong>Location: </strong><%= object.location %>
		<br />
	</td>
	<td>
		<strong>Description: </strong><%=simple_format h object.description %>
		
		<strong>Contact Info: </strong><%= object.contact %><br />
		<strong>WebSite: </strong><%= object.website %><br />
	</td>
</tr>
<tr>
	<td colspan=2 class="eventcolumn">
		<% if !current_user.nil? %>
			<%= link_to "delete", object, :method => :delete, 
	                    :confirm => "You sure you want to delete this event?",
	                    :title => "Delete #{object.id}", :class => "button" %>
		
			<%= link_to "edit", edit_event_path(object), :class => "button" %>
		<br />

		<% end %>
		
	</td>
</tr>

app/views/localevents/edit.html.erb
<h1>Edit Event Entry</h1>

<% if current_user.admin? %>
  <%= form_for(@event) do |f| %>
  
    <%= render 'shared/error_messages', :object => f.object %>

    <table><tr>
	<td class="eventcolumn">
    <div class="field">
      <%= f.label :when %><br />
      <%= f.text_field :when %>
    </div>
    <div class="field">
      <%= f.label :location %><br />
      <%= f.text_field :location %>
    </div>
    <div class="field">
      <%= f.label :contact %><br />
      <%= f.text_field :contact %>
    </div>
    <div class="field">
      <%= f.label :website %><br />
      <%= f.text_field :website, :maxlength=>'40' %>
    </div>
    </td class="eventcolumn">
	<td>
    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name, :maxlength=>'40' %>
    </div>
    <div class="field">
      <%= f.label :description %><br />
	  <%= f.text_area :description, :size => "60x12" %>
    </div>
    </td>
	</tr>
	</table>
  
    <div class="actions">
      <%= f.submit "Submit" %>
    </div>
  <% end %>
<% else %>
  Only Administrators Can Edit An Event...
<% end %>

app/views/localevents/index.html.erb
<h1>Current Local Event Listing</h1>
<br />
<%= link_to "Add New Event", add_event_path %><br /><br />


<ul class="users">
	<table>
	<% 
	@events.each do |event| %>
		<%= render 'event_entry', :object => event %>
	<% end %>
	</table>
</ul>

app/views/localevents/new.html.erb
<h1>Create New Event Entry</h1>
<br />

<% if current_user.admin? %>
  <%= form_for(@newevent) do |f| %>
  
    <%= render 'shared/error_messages', :object => f.object %>
    <table><tr>
	<td class="eventcolumn">
    <div class="field">
      <%= f.label :when %><br />
      <%= f.text_field :when %>
    </div>
    <div class="field">
      <%= f.label :location %><br />
      <%= f.text_field :location %>
    </div>
    <div class="field">
      <%= f.label :contact %><br />
      <%= f.text_field :contact %>
    </div>
    <div class="field">
      <%= f.label :website %><br />
      <%= f.text_field :website, :maxlength=>'40' %>
    </div>
    </td class="eventcolumn">
	<td>
    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name, :maxlength=>'40' %>
    </div>
    <div class="field">
      <%= f.label :description %><br />
	  <%= f.text_area :description, :size => "60x12" %>
    </div>
    </td>
	</tr>
	</table>
    <div class="actions">
      <%= f.submit "Submit" %>
    </div>
  <% end %>
<% else %>
  Only Administrators Can Create A New Event...
<% end %>

app/views/localevents/show.html.erb
<h1>Localevents#show</h1>
<p>Find me in app/views/localevents/show.html.erb</p>