config/routes.rb
Newsample::Application.routes.draw do
  resources :users 
  resources :sessions, :only => [:new, :create, :destroy]
  resources :members
  resources :localevents
  resources :resources
  
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy' 

  match '/contact', :to => 'pages#about'
  
  match '/create_member', :to => 'members#new'
  match '/edit_member', :to => 'members#edit'
  match '/list_members', :to => 'members#index'
  match '/add_member', :to => 'members#new'
  
  match '/add_event', :to => 'localevents#new'
  match '/show_event', :to => 'localevents#show'
  match '/list_events', :to => 'localevents#index'
  match '/edit_event', :to => 'localevents#edit'

  match '/add_resource', :to => 'resources#new'
  match '/list_resources', :to => 'resources#index'
  match '/edit_resource', :to => 'resources#edit'
  
  match '/admin', :to => 'pages#admin'
  match '/construction', :to => "pages#construction"
  root :to => 'pages#home'
end

          

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                 :integer         not null, primary key
#  name               :string(255)
#  fname              :string(255)
#  midinit            :string(255)
#  lname              :string(255)
#  email              :string(255)
#  login              :string(255)
#  homephone          :string(255)
#  cellphone          :string(255)
#  street             :string(255)
#  city               :string(255)
#  state              :string(255)
#  zip                :string(255)
#  startdate          :integer
#  admin              :boolean         default(FALSE)
#  encrypted_password :string(255)
#  salt               :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  teamleader         :boolean
#

require 'digest'

class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation, :admin,
                  :street, :city, :state, :zip, :homephone, :cellphone, 
                  :startdate, :fname, :lname, :teamleader, :login
  
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  startdate_regex = /[12][09][\d]{2}/
  
  validates   :name,  :presence => true,
              :length   => { :maximum => 50 }
            
  validates   :fname, :presence => true
  
  validates   :lname, :presence => true            

        
  validates   :email, :presence => true,  
            :format => { :with => email_regex },
            :uniqueness => { :case_sensitive => false }
      
  validates   :password,  :presence => true, :on => :create
  
   validates   :password,  :confirmation => true ,
                 :length => { :within => 6..40 }, :if => :password_is_not_blank?
                
  validates   :startdate, :presence => true,
              :format => { :with => startdate_regex }
  
  before_save :encrypt_password
  before_save :format_phoneNumbers
    
  default_scope :order => "name asc" 
    
  def password_is_not_blank?
    !password.blank?
  end
  
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end
  
  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    (user && user.has_password?(submitted_password)) ? user : nil
  end
  
  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end
    
  private
    def encrypt_password
      if !password.blank?
        self.salt = make_salt if new_record?
        self.encrypted_password = encrypt(password)
      end
    end
    
    def encrypt(aString)
      secure_hash("#{salt}--#{aString}") 
    end
    
    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end
    
    def secure_hash(aString)
      Digest::SHA2.hexdigest(aString)
    end
    
    def format_phoneNumbers
      # nop for now
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, :except => [:new, :create]
  before_filter :correct_user, :only => [:edit, :update]
  before_filter :admin_user,  :only => [:new, :create, :destroy]
  before_filter :not_if_current_user, :only => :destroy

  def index
    @title = "All users"
    @users = User.paginate(:page => params[:page], :per_page => 80)
  end

  def new
    @title = "Sign Up"
    @newuser = User.new
  end
  
  def edit
    @title = "Edit user"
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
    @title = @user.name
  end
  
  def update
    @user = User.find(params[:id])
    
    # if current user or admin then
    if (@user == current_user) || current_user.admin?
      # clear out password if blank
      if (params[:user][:password] == "")
        params[:user].delete("password")
        params[:user].delete("password_confirmation")
      end
        
      # update model entry with validation
      if @user.update_attributes(params[:user])
        flash[:success] = "Profile updated."
        
        redirect_to @user 
      else
        flash[:failure] = "ERROR: Profile NOT updated."
        @title = "Edit user"
        render :action => "edit"
      end        
    else
      # show not be updated and redirect to home page
      flash[:failure] = "Profile NOT updated.  You must be the user or an administrator."
      redirect to home_path
    end
  end
  
  def create
    @newuser = User.new(params[:user])
    if @newuser.save
      #sign_in @user
      flash[:success] = "Welcome to the Host site!"
      redirect_to users_path 
      # redirect_to current_user        
    else
      @title = "Sign up"
      render 'new'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "This User was destroyed."
    redirect_to users_path
  end

  private 
    def correct_user
      @user = User.find(params[:id])      
      redirect_to(root_path) unless current_user?(@user) || current_user.admin?
    end
  
    def admin_user
      redirect_to(root_path) if current_user.nil?
      redirect_to(root_path) unless current_user.admin?
    end
      
    def not_if_current_user 
      @user = User.find(params[:id])  
      if @user == current_user
        flash[:failure] = "You may not delete yourself..."
        redirect_to(root_path)
      end
    end    
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { :size => 50 })
    gravatar_image_tag(user.email.downcase, :alt => user.name,
                                            :class => 'gravatar',
                                            :gravatar => options)
  end
  
end

app/views/users/_user.html.erb
<li>
	<%= gravatar_for user, :size => 50 %>
 <%= link_to user.name, user %>
  <% if user.admin? %>
   Administrator   
 <% end %>  
</li>

app/views/users/_user_entry.html.erb
<li>
  <tr>
    <td class="tdadmin">
      <% if object.admin? %>
       Admin
      <% else %>    
        -  
      <% end %>
      <br />
      
      <% if object.teamleader? %>
        TeamLead
      <% else %>    
        - 
      <% end %>
    </td>

    <td class="tdgravatar">
      <%= gravatar_for object, :size => 30 %><br />
      <strong><%= mail_to object.email, "Email Me" %></strong>
    </td>
  
  <td class="tdnamefield">
    <strong><%= link_to object.name, object %></strong> <br />
    <strong>Home:</strong> <%= object.homephone %> <br />
    <strong>Cell:</strong> <%= object.cellphone %><br /><br />
  </td>
     
  <td width="20px">
    <% if object == current_user %>
      <%= link_to "edit",  edit_user_path(object), :class => "button" %>
    <% end %>  
  </td>    
  </tr>
</li>

app/views/users/_user_entry_admin.html.erb
<li>
  <tr>
    <td class="tdadmin">
      <% if object.admin? %>
       Admin
      <% else %>    
        -  
      <% end %>
      <br />
      
      <% if object.teamleader? %>
        TeamLead
      <% else %>    
        - 
      <% end %>
    </td>

    <td class="tdgravatar">
      <%= gravatar_for object, :size => 30 %><br />
      <strong><%= mail_to object.email, "Email Me" %></strong>
    </td>
  
  <td class="tdnamefield">
    <strong><%= link_to object.name, object %></strong> <br />
    <strong>Home:</strong> <%= object.homephone %> <br />
    <strong>Cell:</strong> <%= object.cellphone %><br /><br />
  </td>
  
  <td width="20px">
	<% if current_user != object %>
    	<%= link_to "delete", object, :method => :delete, 
	                :confirm => "You sure you want to delete " + object.name + "?",
	                :title => "Delete #{object.name}", 
	                :class => "button" %> <br />
	<% end %>
  </td>
  
  <td width="20px">
    <%= link_to "edit",  edit_user_path(object), :class => "button" %><br />
  </td>    
  </tr>
</li>

app/views/users/edit.html.erb
<h1>Edit user</h1>

<div>
  <%= gravatar_for @user %>
  <a href="http://gravatar.com/emails" target="_blank">change</a>
</div>

<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
   
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  
  <div class="field">
    <%= f.label :fname %>
    <%= f.text_field :fname %>
  </div>
  
  <div class="field">
    <%= f.label :lname %>
    <%= f.text_field :lname %>
  </div>
  
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>        
  
  <div class="field">
    <%= f.label :street %>
    <%= f.text_field :street, :size => 40 %>
  </div>
  
  <table>
    <td>
    <div class="field">
      <%= f.label :city %>, 
      <%= f.text_field :city %>
    </div>
    </td>
    <td>
    <div class="field">
      <%= f.label :state %>, 
      <%= f.text_field :state, :size => 3 %>
    </div>
    </td>
    <td>
    <div class="field">
      <%= f.label :zip %>, 
      <%= f.text_field :zip, :size => 5 %>
    </div>
    </td>
  </table>
   
  <div class="field">
    <%= f.label :homephone %>
    <%= f.text_field :homephone %>
  </div>

  <div class="field">
    <%= f.label :cellphone %>
    <%= f.text_field :cellphone %>
  </div>

  <div class="field">
    <%= f.label :startdate %> (YYYY)
    <%= f.text_field :startdate %>
  </div>

  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>

  <% if current_user.admin? %>
    <div class="field">
      <%= f.label :admin, "Administrator" %><br />
      <%= f.check_box :admin %>
    </div>
    <div class="field">
      <%= f.label :teamleader, "Team Leader" %><br />
      <%= f.check_box :teamleader %>
    </div>
  <% end %>
  
  <div class="actions">
    <%= f.submit "Update" %>
  </div>  
<% end %>

app/views/users/index.html.erb
<h1>All users</h1>

  <% if current_user.admin? %>
    <%= link_to "New User", signup_path %>
 <% end %>


<%= will_paginate %>

<ul class="users">

<table>  
  <% @users.each do |user| %>
    <% if user.fname != "aamaxtest" %>
      <% if current_user.admin? %>
        <%= render 'user_entry_admin', :object => user %>
      <% else %>
        <%= render 'user_entry', :object => user %>
      <% end %>  
     <% end %>
  <% end %>
</table>  

</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<% if current_user.admin? %>
  <%= form_for(@newuser) do |f| %>
  
    <%= render 'shared/error_messages', :object => f.object %>

    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>
  
    <div class="field">
      <%= f.label :fname %>
      <%= f.text_field :fname %>
    </div>
    
    <div class="field">
      <%= f.label :lname %>
      <%= f.text_field :lname %>
    </div>
    <div class="field">
      <%= f.label :email %><br />
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :startdate %> (YYYY)
      <%= f.text_field :startdate %>
    </div>  
    <div class="field">
      <%= f.label :password %><br />
      <%= f.password_field :password %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation, "Confirmation" %><br />
      <%= f.password_field :password_confirmation %>
    </div>
    <div class="actions">
      <%= f.submit "Sign up" %>
    </div>
  <% end %>
<% else %>
  Only Administrators Can Create A New User...
<% end %>

app/views/users/show.html.erb
<table class="profile" summary="Profile information">
  <tr>
    <td class="main">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </td>

    <td class="sidebar round" rowspan="2">
      <strong>Name</strong> <%= @user.name %><br />
      <strong>URL</strong>  <%= link_to user_path(@user), @user %><br />
      <br />
      
      <% if @user.admin? %>
        - Administrator -        
     <% else %>    
        - Normal Member -
     <% end %><br />
     <% if @user.teamleader? %>
        - Team Leader - 
     <% end %>        
      <br />
      <strong>Start Date:</strong> <%= @user.startdate %> <br />
     </td>
  </tr>
  <tr>
    <td class="sidebar round">
      <h3>Address: </h3>
      <%= @user.street %><br />
      <%= @user.city %>
      <% if !@user.city.blank? %>, <% end %> <%= @user.state %> <%= @user.zip %><br />
      <strong>HOME:</strong> <%= @user.homephone %> <br />
      <strong>CELL:</strong> <%= @user.cellphone %>       
    </td>
  </tr>
  <tr>
    <td>
      <strong><%= link_to "Edit User Info", edit_user_path(@user) %></strong>
    </td>
  </tr>
</table>
<br />

  