config/routes.rb
Newsample::Application.routes.draw do
  resources :users 
  resources :sessions, :only => [:new, :create, :destroy]
  resources :members
  resources :localevents
  resources :resources
  
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy' 

  match '/contact', :to => 'pages#about'
  
  match '/create_member', :to => 'members#new'
  match '/edit_member', :to => 'members#edit'
  match '/list_members', :to => 'members#index'
  match '/add_member', :to => 'members#new'
  
  match '/add_event', :to => 'localevents#new'
  match '/show_event', :to => 'localevents#show'
  match '/list_events', :to => 'localevents#index'
  match '/edit_event', :to => 'localevents#edit'

  match '/add_resource', :to => 'resources#new'
  match '/list_resources', :to => 'resources#index'
  match '/edit_resource', :to => 'resources#edit'
  
  match '/admin', :to => 'pages#admin'
  match '/construction', :to => "pages#construction"
  root :to => 'pages#home'
end

          

app/views/resources/_resource_entry.erb
<tr>
	<td width="200px" class="eventcolumn">
	    <strong>Name: </strong><br />
		<%= object.name.capitalize %>
		<br /><br />
		<strong>Contact: </strong><%= object.contact %><br />
		<strong>Phone: </strong><%= object.phone %>
		<br />
	</td>
	<td>
		<strong>WebSite: </strong><%= link_to object.website, object.website %>
		<br /><br />
		<strong>Description: </strong><%=simple_format h object.description %>		
	</td>
</tr>
<tr>
	<td colspan=2 class="eventcolumn">
		<% if !current_user.nil? %>
			<%= link_to "delete", object, :method => :delete, 
	                    :confirm => "You sure you want to delete this resource?",
	                    :title => "Delete #{object.id}", :class => "button" %>
		
			<%= link_to "edit", edit_resource_path(object), :class => "button" %>
		<br />

		<% end %>
		
	</td>
</tr>

app/views/resources/edit.html.erb
<h1>Edit Resource Entry</h1>

<% if current_user.admin? %>
  <%= form_for(@resource) do |f| %>
  
    <%= render 'shared/error_messages', :object => f.object %>

    <table><tr>
	<td class="eventcolumn">
    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :contact %><br />
      <%= f.text_field :contact %>
    </div>
    <div class="field">
      <%= f.label :phone %><br />
      <%= f.text_field :phone %>
    </div>
    <div class="field">
      <%= f.label :website %><br />
      <%= f.text_field :website, :maxlength=>'40' %>
    </div>
    <div class="field">
      <%= f.label :category %><br />
      <%= f.text_field :category %>
    </div>
    </td class="eventcolumn">
	<td>
    <div class="field">
      <%= f.label :description %><br />
	  <%= f.text_area :description, :size => "60x12" %>
    </div>
    </td>
	</tr>
	</table>
  
    <div class="actions">
      <%= f.submit "Submit" %>
    </div>
  <% end %>
<% else %>
  Only Administrators Can Edit A Resource...
<% end %>

app/views/resources/index.html.erb
<h1>Drug Free Draper Resource Listing</h1>
<br />
<% if !current_user.nil? && current_user.admin? %>
	<%= link_to "Add New Resource", add_resource_path %>
<% end %>
<ul class="users">
	<table>
	<% 
	@resources.each do |resource| %>
		<%= render 'resource_entry', :object => resource %>
	<% end %>
	</table>
</ul>

app/views/resources/new.html.erb
<h1>Create Resource Entry</h1>

<% if current_user.admin? %>
  <%= form_for(@newresource) do |f| %>
  
    <%= render 'shared/error_messages', :object => f.object %>

    <table><tr>
	<td class="eventcolumn">
    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :contact %><br />
      <%= f.text_field :contact %>
    </div>
    <div class="field">
      <%= f.label :phone %><br />
      <%= f.text_field :phone %>
    </div>
    <div class="field">
      <%= f.label :website %><br />
      <%= f.text_field :website, :maxlength=>'40' %>
    </div>
    <div class="field">
      <%= f.label :category %><br />
      <%= f.text_field :category %>
    </div>
    </td class="eventcolumn">
	<td>
    <div class="field">
      <%= f.label :description %><br />
	  <%= f.text_area :description, :size => "60x12" %>
    </div>
    </td>
	</tr>
	</table>
  
    <div class="actions">
      <%= f.submit "Submit" %>
    </div>
  <% end %>
<% else %>
  Only Administrators Can Create A Resource...
<% end %>