config/routes.rb
Newsample::Application.routes.draw do
  resources :users 
  resources :sessions, :only => [:new, :create, :destroy]
  resources :members
  resources :localevents
  resources :resources
  
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy' 

  match '/contact', :to => 'pages#about'
  
  match '/create_member', :to => 'members#new'
  match '/edit_member', :to => 'members#edit'
  match '/list_members', :to => 'members#index'
  match '/add_member', :to => 'members#new'
  
  match '/add_event', :to => 'localevents#new'
  match '/show_event', :to => 'localevents#show'
  match '/list_events', :to => 'localevents#index'
  match '/edit_event', :to => 'localevents#edit'

  match '/add_resource', :to => 'resources#new'
  match '/list_resources', :to => 'resources#index'
  match '/edit_resource', :to => 'resources#edit'
  
  match '/admin', :to => 'pages#admin'
  match '/construction', :to => "pages#construction"
  root :to => 'pages#home'
end

          

app/views/layouts/_footer.html.erb
 <footer  class="round">
	<table>
		<tr>
			<td>
			  <br />
		      <strong>&nbsp;&nbsp;&nbsp;<%= mail_to "aamax@xmission.com", "Email WebMaster" %> 
		        Phone: (801) 502-4745</strong><br />
			  <br />
			</td>
		</tr>
	</table>
  </footer>

app/views/layouts/_header.html.erb
<header>
	<%= link_to logo, root_path %>
	<%= render 'layouts/menu' %>

		  <% if signed_in? %>
		    <div class="UserName">
		      <%= link_to "Hello " + current_user.fname.titleize + "!", current_user %>
		    </div>
		  <% end %>
</header>

app/views/layouts/_menu.html.erb
<!-- Grey Menu -->
<div id="menu_wrapper" class="blue">
	<div class="left"></div>
	<ul id="menu">
		<% if signed_in? %>
		    <li><%= link_to "Sign out", signout_path, :method => :delete %></li>
			<li><%= link_to "Users", users_path %></li>
			<li><%= link_to "Mailing List", list_members_path %></li>
			<li><%= link_to "Events List", list_events_path %></li>
			<li><%= link_to "Resource List", list_resources_path %></li>
		<% else %>
			<li><%= link_to "Sign in", signin_path %></li>
			<li><%= link_to "Contact Us", contact_path %></li>
			<li><%= link_to "Resources", list_resources_path %></li>
		<% end %>
	</ul>
</div>

app/views/layouts/_stylesheets.html.erb
    <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->    
    <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
    <%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
        
    <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
    <%= stylesheet_link_tag 'custom', :media => 'screen' %>  
    <%= stylesheet_link_tag 'collapser', :media => 'screen' %>

app/views/layouts/_user.html.erb
<li>
  <% if object.admin? %>
    <td width="15px">Admin</td>
    </td>
 <% else %>    
 		<td> - </td>
 <% end %>

	<td width="10px"><%= gravatar_for object, :size => 30 %></td>
  <td width="25px"><%= link_to object.name, object %></td>
  
  
  <% if current_user.admin? %>
    <td width="20px">
    	<%= link_to "delete", object, :method => :delete, 
    				:confirm => "You sure?",
                    :title => "Delete #{object.name}" %>
                            		
    </td>
    <td width="20px">
    	<%= link_to "edit",  edit_user_path(object) %>
    </td>
  <% end %>
  
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= javascript_include_tag :application %>
    <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js" %>
    <%= javascript_include_tag "jquery.collapse.js" %>
    <%= javascript_include_tag "jquery.cookie.js" %>
    
    <script>document.documentElement.className = "js";</script>
    
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>   
  </head>
  <body>
    <div class="container">    
   		<%= render 'layouts/header' %> 
   		
      <section class="round">
      
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, :class => "flash #{key}") %>
        <% end %>
        
        <%= yield %>
        
      </section>
      
	  <%= render 'layouts/footer' %> 
      
    </div> 
<%= debug(params) if Rails.env.development? %>    
  </body>
</html>